prog:afficherperso.o afficher.o
	gcc   afficherperso.o afficher.o -o prog -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf 
afficherperso.o:afficherperso.c
	gcc -c afficherperso.c
afficher.o:afficher.c
	gcc -c afficher.c
