

game:main.o partage.o
	gcc main.o partage.o -o game  -lSDL -lSDL_image -lSDL_mixer -g 

main.o:main.c
	gcc main.c -c  -lSDL -lSDL_image -lSDL_mixer -g


partage.o:partage.c
	gcc partage.c -c -lSDL -lSDL_image -lSDL_mixer -g
